# Generated by Django 2.2.4 on 2019-09-04 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("forum", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="forumtopic",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="author",
            ),
        )
    ]
