# Generated by Django 2.2.4 on 2019-08-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=510, verbose_name="title")),
                ("text", models.CharField(max_length=1020, verbose_name="text")),
                ("date", models.DateField(verbose_name="date")),
            ],
            options={"verbose_name": "News", "verbose_name_plural": "News"},
        )
    ]
