# Generated by Django 2.2.4 on 2019-09-01 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("common", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("saved", models.BooleanField(default=True)),
                ("about", models.TextField(verbose_name="about")),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="SettingMedia",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("media_file", models.FileField(upload_to="")),
                (
                    "setting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.SiteSetting",
                        verbose_name="setting",
                    ),
                ),
            ],
            options={"verbose_name": "setting"},
        ),
    ]
