# Generated by Django 2.2.4 on 2019-09-03 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("common", "0002_settingmedia_sitesetting")]

    operations = [
        migrations.CreateModel(
            name="SettingImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_file", models.ImageField(upload_to="common/images")),
            ],
            options={
                "verbose_name": "setting image",
                "verbose_name_plural": "setting images",
            },
        ),
        migrations.CreateModel(
            name="SettingVideo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_file", models.FileField(upload_to="common/videos")),
            ],
            options={
                "verbose_name": "setting video",
                "verbose_name_plural": "setting videos",
            },
        ),
        migrations.RemoveField(model_name="sitesetting", name="saved"),
        migrations.DeleteModel(name="SettingMedia"),
        migrations.AddField(
            model_name="settingvideo",
            name="setting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="videos",
                to="common.SiteSetting",
                verbose_name="settings",
            ),
        ),
        migrations.AddField(
            model_name="settingimage",
            name="setting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="common.SiteSetting",
                verbose_name="setting",
            ),
        ),
    ]
