# Generated by Django 2.2.4 on 2019-10-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("common", "0004_auto_20190914_1106")]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="status",
            field=models.CharField(
                choices=[("processed", "processed"), ("in progress", "in progress")],
                default="in progress",
                max_length=127,
                verbose_name="status",
            ),
        )
    ]
