# Generated by Django 2.2.4 on 2020-03-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("common", "0005_feedback_status")]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="text",
            field=models.TextField(verbose_name="text"),
        )
    ]
